package practica3ipc;

import java.awt.Graphics;
import java.awt.Image;
import java.awt.Rectangle;
import java.awt.event.KeyEvent;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author dayan
 */
public class Juego extends javax.swing.JFrame {

    FondoImagen fondo = new FondoImagen();
    static int posicionx;
    static int posiciony;
    static int velocidadnave;
    static int conteoverde1;
    static int conteoverde2;
    static int conteoverde3;
    static int conteoverde4;
    static int conteoverde5;
    static int conteoverde6;
    static int conteoverde7;
    static int conteoverde8;
    static int conteorosa1;
    static int conteorosa2;
    static int conteorosa3;
    static int conteorosa4;
    static int conteorosa5;
    static int conteorosa6;
    static int conteorosa7;
    static int conteorosa8;
    static int conteorosado1;
    static int conteorosado2;
    static int conteorosado3;
    static int conteorosado4;
    static int conteorosado5;
    static int conteorosado6;
    static int conteorosado7;
    static int conteorosado8;
    static int conteoroj1;
    static int conteoroj2;
    static int conteoroj3;
    static int conteoroj4;
    static int conteoroj5;
    static int conteoroj6;
    static int conteoroj7;
    static int conteoroj8;
    static int conteorojo1;
    static int conteorojo2;
    static int conteorojo3;
    static int conteorojo4;
    static int conteorojo5;
    static int conteorojo6;
    static int conteorojo7;
    static int conteorojo8;
    static boolean pasar = true;
    static Disparo disparo;
    static boolean comprobacion;

    public Juego() {
        this.setContentPane(fondo);
        initComponents();
        puntos.setText("" + Practica3IPC.puntos);
        ImageIcon nose = new ImageIcon(getClass().getResource("/Imagenes/verdeoficial.png"));
        ImageIcon imagene = new ImageIcon(nose.getImage().getScaledInstance(Juego.Otro.getWidth(), Juego.Otro.getHeight(), Image.SCALE_DEFAULT));
        Otro.setIcon(imagene);
        Verde2.setIcon(imagene);
        Verde3.setIcon(imagene);
        Verde4.setIcon(imagene);
        Verde5.setIcon(imagene);
        Verde6.setIcon(imagene);
        Verde7.setIcon(imagene);
        Verde8.setIcon(imagene);
        ImageIcon extrarosa = new ImageIcon(getClass().getResource("/Imagenes/rosa.png"));
        ImageIcon rosado = new ImageIcon(extrarosa.getImage().getScaledInstance(Juego.rosa1.getWidth(), Juego.rosa1.getHeight(), Image.SCALE_DEFAULT));
        rosa1.setIcon(rosado);
        rosa2.setIcon(rosado);
        rosa3.setIcon(rosado);
        rosa4.setIcon(rosado);
        rosa5.setIcon(rosado);
        rosa6.setIcon(rosado);
        rosa7.setIcon(rosado);
        rosa8.setIcon(rosado);
        rosado1.setIcon(rosado);
        rosado2.setIcon(rosado);
        rosado3.setIcon(rosado);
        rosado4.setIcon(rosado);
        rosado5.setIcon(rosado);
        rosado6.setIcon(rosado);
        rosado7.setIcon(rosado);
        rosado8.setIcon(rosado);
        ImageIcon navee = new ImageIcon(getClass().getResource("/Imagenes/nave_1.png"));
        ImageIcon imagen = new ImageIcon(navee.getImage().getScaledInstance(Nave.getWidth(), Nave.getHeight(), Image.SCALE_DEFAULT));
        Nave.setIcon(imagen);
        ImageIcon rojo = new ImageIcon(getClass().getResource("/Imagenes/rojo.png"));
        ImageIcon imagenrojo = new ImageIcon(rojo.getImage().getScaledInstance(roj1.getWidth(), roj1.getHeight(), Image.SCALE_DEFAULT));
        roj1.setIcon(imagenrojo);
        roj2.setIcon(imagenrojo);
        roj3.setIcon(imagenrojo);
        roj4.setIcon(imagenrojo);
        roj5.setIcon(imagenrojo);
        roj6.setIcon(imagenrojo);
        roj7.setIcon(imagenrojo);
        roj8.setIcon(imagenrojo);
        rojo1.setIcon(imagenrojo);
        rojo2.setIcon(imagenrojo);
        rojo3.setIcon(imagenrojo);
        rojo4.setIcon(imagenrojo);
        rojo5.setIcon(imagenrojo);
        rojo6.setIcon(imagenrojo);
        rojo7.setIcon(imagenrojo);
        rojo8.setIcon(imagenrojo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Nave = new javax.swing.JLabel();
        Labelabajo = new javax.swing.JLabel();
        Otro = new javax.swing.JLabel();
        Labelarriba = new javax.swing.JLabel();
        Verde2 = new javax.swing.JLabel();
        Verde3 = new javax.swing.JLabel();
        Verde4 = new javax.swing.JLabel();
        Verde5 = new javax.swing.JLabel();
        Verde8 = new javax.swing.JLabel();
        Verde6 = new javax.swing.JLabel();
        Verde7 = new javax.swing.JLabel();
        rosa1 = new javax.swing.JLabel();
        rosa2 = new javax.swing.JLabel();
        rosa3 = new javax.swing.JLabel();
        rosa4 = new javax.swing.JLabel();
        rosa5 = new javax.swing.JLabel();
        rosa8 = new javax.swing.JLabel();
        rosa7 = new javax.swing.JLabel();
        rosa6 = new javax.swing.JLabel();
        rosado1 = new javax.swing.JLabel();
        rosado2 = new javax.swing.JLabel();
        rosado3 = new javax.swing.JLabel();
        rosado4 = new javax.swing.JLabel();
        rosado5 = new javax.swing.JLabel();
        rosado6 = new javax.swing.JLabel();
        rosado7 = new javax.swing.JLabel();
        rosado8 = new javax.swing.JLabel();
        topaste = new javax.swing.JLabel();
        roj1 = new javax.swing.JLabel();
        roj2 = new javax.swing.JLabel();
        roj3 = new javax.swing.JLabel();
        roj4 = new javax.swing.JLabel();
        roj5 = new javax.swing.JLabel();
        roj6 = new javax.swing.JLabel();
        roj7 = new javax.swing.JLabel();
        roj8 = new javax.swing.JLabel();
        rojo1 = new javax.swing.JLabel();
        rojo4 = new javax.swing.JLabel();
        rojo3 = new javax.swing.JLabel();
        rojo2 = new javax.swing.JLabel();
        rojo8 = new javax.swing.JLabel();
        rojo7 = new javax.swing.JLabel();
        rojo6 = new javax.swing.JLabel();
        rojo5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Tiempo = new java.awt.Label();
        jLabel4 = new javax.swing.JLabel();
        puntos = new java.awt.Label();
        velocidadjuego = new java.awt.Label();
        mastiempoo = new javax.swing.JLabel();
        maspuntos = new javax.swing.JLabel();
        menospuntos = new javax.swing.JLabel();
        menostiempo = new javax.swing.JLabel();
        masvelocidad = new javax.swing.JLabel();
        congelarl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Invasores Espaciales");
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        Otro.setBackground(new java.awt.Color(204, 0, 153));
        Otro.setText("jLabel1");

        Verde2.setText("jLabel1");

        Verde3.setText("jLabel2");

        Verde4.setText("jLabel6");

        Verde5.setText("jLabel7");

        Verde8.setText("jLabel8");

        Verde6.setText("jLabel9");

        Verde7.setText("jLabel");

        rosa1.setForeground(new java.awt.Color(0, 0, 0));
        rosa1.setText("jLabel1");

        rosa2.setForeground(new java.awt.Color(0, 0, 0));
        rosa2.setText("jLabel2");

        rosa3.setForeground(new java.awt.Color(0, 0, 0));
        rosa3.setText("jLabel6");

        rosa4.setForeground(new java.awt.Color(0, 0, 0));
        rosa4.setText("jLabel7");

        rosa5.setForeground(new java.awt.Color(0, 0, 0));
        rosa5.setText("jLabel8");

        rosa8.setForeground(new java.awt.Color(0, 0, 0));
        rosa8.setText("jLabel9");

        rosa7.setForeground(new java.awt.Color(0, 0, 0));
        rosa7.setText("jLabel1");

        rosa6.setForeground(new java.awt.Color(0, 0, 0));
        rosa6.setText("jLabel2");

        rosado1.setText("jLabel1");

        rosado2.setText("jLabel2");

        rosado3.setText("jLabel6");

        rosado4.setText("jLabel7");

        rosado5.setText("jLabel8");

        rosado6.setText("jLabel");

        rosado7.setText("jLabel1");

        rosado8.setText("jLabel1");

        roj1.setText("jLabel1");

        roj2.setText("jLabel2");

        roj3.setText("jLabel6");

        roj4.setText("jLabel7");

        roj5.setText("jLabel8");

        roj6.setText("jLabel9");

        roj7.setText("jLabel1");

        roj8.setText("jLabel1");

        rojo1.setText("jLabel1");

        rojo4.setText("jLabel1");

        rojo3.setText("jLabel1");

        rojo2.setText("jLabel1");

        rojo8.setText("jLabel1");

        rojo7.setText("jLabel1");

        rojo6.setText("jLabel1");

        rojo5.setText("jLabel1");

        jPanel1.setBackground(new java.awt.Color(0, 102, 0));

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Puntos");

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Tiempo");

        Tiempo.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        Tiempo.setText("label1");

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Velocidad");

        puntos.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        puntos.setText("label1");

        velocidadjuego.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        velocidadjuego.setText("label1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(584, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(puntos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(velocidadjuego, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(117, 117, 117)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(Tiempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 74, 74))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Tiempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(puntos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(velocidadjuego, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Labelabajo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Labelarriba, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(267, 267, 267)
                                        .addComponent(menospuntos, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(38, 38, 38)
                                        .addComponent(topaste, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(47, 47, 47)
                                                .addComponent(mastiempoo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(132, 132, 132)
                                                .addComponent(masvelocidad, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addComponent(Nave, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(maspuntos, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(177, 177, 177)))
                        .addComponent(congelarl, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(195, 195, 195)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Verde6, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(24, 24, 24)
                                        .addComponent(rosa6, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(rosado6, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(Verde8, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(rosa8, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(rosado8, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(Verde7, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(24, 24, 24)
                                            .addComponent(rosa7, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(rosado7, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(Otro, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(Verde2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(Verde3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                    .addComponent(rosa1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(rosado1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                    .addComponent(rosa2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(rosado2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                    .addComponent(rosa3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(rosado3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(roj8, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(30, 30, 30)
                                        .addComponent(rojo8, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(roj7, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(rojo7, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(roj3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(30, 30, 30)
                                                .addComponent(rojo3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(roj2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(30, 30, 30)
                                                .addComponent(rojo2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(roj4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(roj5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(roj6, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(rojo6, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(roj1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(30, 30, 30)
                                            .addComponent(rojo1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(Verde4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rosa4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rosado4, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(100, 100, 100)
                                .addComponent(rojo4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(Verde5, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rosa5, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rosado5, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(100, 100, 100)
                                .addComponent(rojo5, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(25, 25, 25)))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(329, 329, 329)
                    .addComponent(menostiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(619, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Labelarriba, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Otro, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(roj1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rojo1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rosado1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rosa1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(masvelocidad, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Verde2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(roj2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rojo2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rosado2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rosa2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(13, 13, 13)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Verde3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(roj3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rojo3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rosado3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rosa3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(12, 12, 12))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(mastiempoo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(65, 65, 65)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Verde4, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(roj4, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rojo4, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rosado4, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rosa4, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(congelarl, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(topaste, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Nave, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rojo5, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(roj5, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(rosado5, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(rosa5, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Verde5, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rosado6, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(roj6, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rojo6, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rosa6, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Verde6, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(menospuntos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rojo7, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(roj7, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(rosado7, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Verde7, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(rosa7, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rosa8, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rosado8, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(roj8, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rojo8, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Verde8, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                        .addComponent(Labelabajo, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(maspuntos, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(371, Short.MAX_VALUE)
                    .addComponent(menostiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(244, 244, 244)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        int tecla = evt.getKeyCode();
        posicionx = Nave.getX();
        posiciony = Nave.getY();
        velocidadnave = 10;
        Rectangle arriba = Labelarriba.getBounds();
        Rectangle abajo = Labelabajo.getBounds();
        Rectangle rec = Nave.getBounds();
        if (Configuracion.velo == 0) {
            velocidadnave = 10;

            if (Masvelocidad.mover) {
                velocidadnave = 20;
                Masvelocidad.mover = false;
            }

        }
        if (Configuracion.velo == 1) {
            velocidadnave = 25;

            if (Masvelocidad.mover) {
                velocidadnave = 50;
                Masvelocidad.mover = false;
            }

        }
        if (Congelar.nomover) {
            velocidadnave = 0;
            
        }

        switch (tecla) {
            case KeyEvent.VK_UP:
                if (!rec.intersects(arriba)) {

                    Nave.setLocation(posicionx, posiciony - velocidadnave);

                }
                break;
            case KeyEvent.VK_DOWN:
                if (!rec.intersects(abajo)) {

                    Nave.setLocation(posicionx, posiciony + velocidadnave);
                }
                break;

            case KeyEvent.VK_SPACE:
                int velocidad = 0;
                if (Configuracion.velo == 0) {
                    velocidad = 17;
                }
                if (Configuracion.velo == 1) {
                    velocidad = 8;
                }
                disparo = new Disparo(rec, this, velocidad);

                disparo.start();

                comprobacion = true;
                this.setLayout(null);
                break;
            case KeyEvent.VK_ESCAPE:

                if (comprobacion) {
                    disparo.suspend();
                    Principal.tiempo.suspend();
                    Principal.movimineto.suspend();
                    Principal.moverosa.suspend();
                    Principal.moverosado.suspend();
                    Principal.moveroj.suspend();
                    Principal.moverojo.suspend();
                    if (Pausa.pausamastiempo) {
                        Principal.mastiempo.suspend();
                    }
                    if (Pausa.pausamenostiempo) {
                        Principal.menostiempo.suspend();
                    }
                    if (Pausa.pausamenospuntos) {
                        Principal.menospuntos.suspend();
                    }
                    if (Pausa.pausamaspuntos) {
                        Principal.maspuntos.suspend();
                    }
                    if (Pausa.pausamasvelocidad) {
                        Principal.masvelocidaad.suspend();
                    }
                }
                if (!comprobacion) {
                    Principal.tiempo.suspend();
                    Principal.movimineto.suspend();
                    Principal.moverosa.suspend();
                    Principal.moverosado.suspend();
                    Principal.moveroj.suspend();
                    Principal.moverojo.suspend();
                    if (Pausa.pausamastiempo) {
                        Principal.mastiempo.suspend();
                    }
                    if (Pausa.pausamenostiempo) {
                        Principal.menostiempo.suspend();
                    }
                    if (Pausa.pausamenospuntos) {
                        Principal.menospuntos.suspend();
                    }
                    if (Pausa.pausamaspuntos) {
                        Principal.maspuntos.suspend();
                    }
                    if (Pausa.pausamasvelocidad) {
                        Principal.masvelocidaad.suspend();
                    }
                }
                Pausa pausa = new Pausa();
                pausa.setVisible(true);
                pausa.setLocationRelativeTo(null);
                break;
        }


    }//GEN-LAST:event_formKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Juego().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel Labelabajo;
    public static javax.swing.JLabel Labelarriba;
    public static javax.swing.JLabel Nave;
    public static javax.swing.JLabel Otro;
    public static java.awt.Label Tiempo;
    public static javax.swing.JLabel Verde2;
    public static javax.swing.JLabel Verde3;
    public static javax.swing.JLabel Verde4;
    public static javax.swing.JLabel Verde5;
    public static javax.swing.JLabel Verde6;
    public static javax.swing.JLabel Verde7;
    public static javax.swing.JLabel Verde8;
    public static javax.swing.JLabel congelarl;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JLabel maspuntos;
    public static javax.swing.JLabel mastiempoo;
    public static javax.swing.JLabel masvelocidad;
    public static javax.swing.JLabel menospuntos;
    public static javax.swing.JLabel menostiempo;
    public static java.awt.Label puntos;
    public static javax.swing.JLabel roj1;
    public static javax.swing.JLabel roj2;
    public static javax.swing.JLabel roj3;
    public static javax.swing.JLabel roj4;
    public static javax.swing.JLabel roj5;
    public static javax.swing.JLabel roj6;
    public static javax.swing.JLabel roj7;
    public static javax.swing.JLabel roj8;
    public static javax.swing.JLabel rojo1;
    public static javax.swing.JLabel rojo2;
    public static javax.swing.JLabel rojo3;
    public static javax.swing.JLabel rojo4;
    public static javax.swing.JLabel rojo5;
    public static javax.swing.JLabel rojo6;
    public static javax.swing.JLabel rojo7;
    public static javax.swing.JLabel rojo8;
    public static javax.swing.JLabel rosa1;
    public static javax.swing.JLabel rosa2;
    public static javax.swing.JLabel rosa3;
    public static javax.swing.JLabel rosa4;
    public static javax.swing.JLabel rosa5;
    public static javax.swing.JLabel rosa6;
    public static javax.swing.JLabel rosa7;
    public static javax.swing.JLabel rosa8;
    public static javax.swing.JLabel rosado1;
    public static javax.swing.JLabel rosado2;
    public static javax.swing.JLabel rosado3;
    public static javax.swing.JLabel rosado4;
    public static javax.swing.JLabel rosado5;
    public static javax.swing.JLabel rosado6;
    public static javax.swing.JLabel rosado7;
    public static javax.swing.JLabel rosado8;
    public static javax.swing.JLabel topaste;
    public static java.awt.Label velocidadjuego;
    // End of variables declaration//GEN-END:variables

    class FondoImagen extends JPanel {

        private Image imagen;

        @Override
        public void paint(Graphics g) {
            imagen = new ImageIcon(getClass().getResource("/Imagenes/fondo.jpg")).getImage();
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            setOpaque(false);
            super.paint(g);

        }
    }

}
