/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica3ipc;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author dayan
 */
public class Pausa extends javax.swing.JFrame {

    static boolean pausamastiempo = false;
    static boolean pausamenostiempo = false;
    static boolean pausamaspuntos = false;
    static boolean pausamenospuntos = false;
    static boolean pausamasvelocidad = false;
    static boolean pausamenosvelocidad = false;

    public Pausa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Continuar = new javax.swing.JButton();
        Terminar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pausa");

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Good Times", 2, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Pausa");

        Continuar.setBackground(new java.awt.Color(0, 102, 0));
        Continuar.setForeground(new java.awt.Color(0, 0, 0));
        Continuar.setText("Continuar juego");
        Continuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContinuarActionPerformed(evt);
            }
        });

        Terminar.setBackground(new java.awt.Color(0, 102, 0));
        Terminar.setForeground(new java.awt.Color(0, 0, 0));
        Terminar.setText("Regresar al Menú Principal");
        Terminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TerminarActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/extra azul.png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/extra azul.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(Terminar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel2)
                        .addGap(88, 88, 88)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Continuar)
                            .addComponent(jLabel1))))
                .addContainerGap(122, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(57, 57, 57)
                .addComponent(Continuar)
                .addGap(47, 47, 47)
                .addComponent(Terminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TerminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TerminarActionPerformed
        if (Juego.comprobacion) {
            Principal.tiempo.stop();
            Juego.disparo.stop();
            Principal.movimineto.stop();
            Principal.moverosa.stop();
            Juego.disparo.labeldisparo.setVisible(false);
            Principal.moverosado.stop();
            Principal.moveroj.stop();
            Principal.moverojo.stop();
            if (pausamastiempo) {
                Principal.mastiempo.stop();
                Principal.mastiempo.labeltiempo.setVisible(false);
            }
            if (pausamenostiempo) {
                Principal.menostiempo.stop();
                Principal.menostiempo.labeltiempo.setVisible(false);
            }
            if (pausamenospuntos) {
                Principal.menospuntos.stop();
                Principal.menospuntos.labelpuntos.setVisible(false);
            }
            if (pausamaspuntos) {
                Principal.maspuntos.stop();
                Principal.maspuntos.labelpuntos.setVisible(false);
            }
            if (pausamasvelocidad) {
                Principal.masvelocidaad.stop();
                Principal.masvelocidaad.labelvelocidad.setVisible(false);
            }
             if (pausamenosvelocidad) {
                Principal.congelar.stop();
                Principal.congelar.labelvelocidad.setVisible(false);
            }
        }
        if (!Juego.comprobacion) {
            Principal.movimineto.stop();
            Principal.tiempo.stop();
            Principal.moverosa.stop();
            Principal.moverosado.stop();
            Principal.moveroj.stop();
            Principal.moverojo.stop();
            if (pausamastiempo) {
                Principal.mastiempo.stop();
            }
            if (pausamenostiempo) {
                Principal.menostiempo.stop();
            }
            if (pausamenospuntos) {
                Principal.menospuntos.stop();
            }
            if (pausamaspuntos) {
                Principal.maspuntos.stop();
            }
            if (pausamasvelocidad) {
                Principal.masvelocidaad.stop();

            }
             if (pausamenosvelocidad) {
                Principal.congelar.stop();
            }
        }
        Principal principal = new Principal();
        principal.setVisible(true);
        principal.setLocationRelativeTo(null);
        Principal.tiempodejuego = "hola";
        Principal.juego.setVisible(false);
        Practica3IPC.puntos = 0;
        Juego.puntos.setText("" + Practica3IPC.puntos);
        imagenes();
        ver();
        conteo();

        this.setVisible(false);
    }//GEN-LAST:event_TerminarActionPerformed

    private void ContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContinuarActionPerformed

        if (Juego.comprobacion) {
            Principal.tiempo.resume();
            Juego.disparo.resume();
            Principal.movimineto.resume();
            Principal.moverosa.resume();
            Principal.moverosado.resume();
            Principal.moveroj.resume();
            Principal.moverojo.resume();
            if (pausamastiempo) {
                Principal.mastiempo.resume();
            }
            if (pausamenostiempo) {
                Principal.menostiempo.resume();
            }
            if (pausamenospuntos) {
                Principal.menospuntos.resume();
            }
            if (pausamaspuntos) {
                Principal.maspuntos.resume();
            }
            if (pausamasvelocidad) {
                Principal.masvelocidaad.resume();
            }
            if (pausamenosvelocidad) {
                Principal.congelar.resume();
            }
        }
        if (!Juego.comprobacion) {
            Principal.tiempo.resume();
            Principal.movimineto.resume();
            Principal.moverosa.resume();
            Principal.moverosado.resume();
            Principal.moveroj.resume();
            Principal.moverojo.resume();
            if (pausamastiempo) {
                Principal.mastiempo.resume();
            }
            if (pausamenostiempo) {
                Principal.menostiempo.resume();
            }
            if (pausamenospuntos) {
                Principal.menospuntos.resume();
            }
            if (pausamaspuntos) {
                Principal.maspuntos.resume();
            }
            if (pausamasvelocidad) {
                Principal.masvelocidaad.resume();

            }
             if (pausamenosvelocidad) {
                Principal.congelar.resume();
            }
        }
        this.setVisible(false);
    }//GEN-LAST:event_ContinuarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pausa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pausa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pausa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pausa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pausa().setVisible(true);
            }
        });
    }

    public void imagenes() {
        Tiempo.tiempocongelar=0;
        Tiempo.tiempocontador=0;
        Pausa.pausamastiempo=false;
        Pausa.pausamenostiempo=false;
        Pausa.pausamaspuntos=false;
        Pausa.pausamenospuntos=false;
        Pausa.pausamenospuntos=false;
        Pausa.pausamasvelocidad=false;
        Pausa.pausamenosvelocidad=false;
        Configuracion.velo = 0;
        Juego.Nave.setLocation(12, 347);
        ImageIcon nose = new ImageIcon(getClass().getResource("/Imagenes/verdeoficial.png"));
        ImageIcon imagene = new ImageIcon(nose.getImage().getScaledInstance(Juego.Otro.getWidth(), Juego.Otro.getHeight(), Image.SCALE_DEFAULT));
        Juego.Otro.setIcon(imagene);
        Juego.Verde2.setIcon(imagene);
        Juego.Verde3.setIcon(imagene);
        Juego.Verde4.setIcon(imagene);
        Juego.Verde5.setIcon(imagene);
        Juego.Verde6.setIcon(imagene);
        Juego.Verde7.setIcon(imagene);
        Juego.Verde8.setIcon(imagene);
        Juego.Otro.setBounds(613, 85, 52, 54);
        Juego.Verde2.setBounds(613, 155, 52, 54);
        Juego.Verde3.setBounds(613, 221, 52, 54);
        Juego.Verde4.setBounds(613, 287, 52, 54);
        Juego.Verde5.setBounds(613, 347, 52, 54);
        Juego.Verde6.setBounds(613, 427, 52, 54);
        Juego.Verde7.setBounds(613, 493, 52, 54);
        Juego.Verde8.setBounds(613, 559, 52, 54);
        Juego.Otro.setVisible(true);
        Juego.Verde2.setVisible(true);
        Juego.Verde3.setVisible(true);
        Juego.Verde4.setVisible(true);
        Juego.Verde5.setVisible(true);
        Juego.Verde6.setVisible(true);
        Juego.Verde7.setVisible(true);
        Juego.Verde8.setVisible(true);
        ImageIcon extrarosa = new ImageIcon(getClass().getResource("/Imagenes/rosa.png"));
        ImageIcon rosado = new ImageIcon(extrarosa.getImage().getScaledInstance(Juego.rosa1.getWidth(), Juego.rosa1.getHeight(), Image.SCALE_DEFAULT));
        Juego.rosa1.setIcon(rosado);
        Juego.rosa2.setIcon(rosado);
        Juego.rosa3.setIcon(rosado);
        Juego.rosa4.setIcon(rosado);
        Juego.rosa5.setIcon(rosado);
        Juego.rosa6.setIcon(rosado);
        Juego.rosa7.setIcon(rosado);
        Juego.rosa8.setIcon(rosado);
        Juego.rosa1.setBounds(689, 85, 52, 54);
        Juego.rosa2.setBounds(689, 155, 52, 54);
        Juego.rosa3.setBounds(689, 221, 52, 54);
        Juego.rosa4.setBounds(689, 287, 52, 54);
        Juego.rosa5.setBounds(689, 347, 52, 54);
        Juego.rosa6.setBounds(689, 427, 52, 54);
        Juego.rosa7.setBounds(689, 493, 52, 54);
        Juego.rosa8.setBounds(689, 559, 52, 54);
        Juego.rosa1.setVisible(true);
        Juego.rosa2.setVisible(true);
        Juego.rosa3.setVisible(true);
        Juego.rosa4.setVisible(true);
        Juego.rosa5.setVisible(true);
        Juego.rosa6.setVisible(true);
        Juego.rosa7.setVisible(true);
        Juego.rosa8.setVisible(true);
        Juego.rosado1.setIcon(rosado);
        Juego.rosado2.setIcon(rosado);
        Juego.rosado3.setIcon(rosado);
        Juego.rosado4.setIcon(rosado);
        Juego.rosado5.setIcon(rosado);
        Juego.rosado6.setIcon(rosado);
        Juego.rosado7.setIcon(rosado);
        Juego.rosado8.setIcon(rosado);
        Juego.rosado1.setBounds(753, 85, 52, 54);
        Juego.rosado2.setBounds(753, 155, 52, 54);
        Juego.rosado3.setBounds(753, 221, 52, 54);
        Juego.rosado4.setBounds(753, 287, 52, 54);
        Juego.rosado5.setBounds(753, 347, 52, 54);
        Juego.rosado6.setBounds(753, 427, 52, 54);
        Juego.rosado7.setBounds(753, 493, 52, 54);
        Juego.rosado8.setBounds(753, 559, 52, 54);
        Juego.rosado1.setVisible(true);
        Juego.rosado2.setVisible(true);
        Juego.rosado3.setVisible(true);
        Juego.rosado4.setVisible(true);
        Juego.rosado5.setVisible(true);
        Juego.rosado6.setVisible(true);
        Juego.rosado7.setVisible(true);
        Juego.rosado8.setVisible(true);
        ImageIcon extrarojo = new ImageIcon(getClass().getResource("/Imagenes/rojo.png"));
        ImageIcon rojo = new ImageIcon(extrarojo.getImage().getScaledInstance(Juego.rosa1.getWidth(), Juego.rosa1.getHeight(), Image.SCALE_DEFAULT));
        Juego.roj1.setIcon(rojo);
        Juego.roj2.setIcon(rojo);
        Juego.roj3.setIcon(rojo);
        Juego.roj4.setIcon(rojo);
        Juego.roj5.setIcon(rojo);
        Juego.roj6.setIcon(rojo);
        Juego.roj7.setIcon(rojo);
        Juego.roj8.setIcon(rojo);
        Juego.roj1.setBounds(823, 85, 52, 54);
        Juego.roj2.setBounds(823, 155, 52, 54);
        Juego.roj3.setBounds(823, 221, 52, 54);
        Juego.roj4.setBounds(823, 287, 52, 54);
        Juego.roj5.setBounds(823, 347, 52, 54);
        Juego.roj6.setBounds(823, 427, 52, 54);
        Juego.roj7.setBounds(823, 493, 52, 54);
        Juego.roj8.setBounds(823, 559, 52, 54);
        Juego.roj1.setVisible(true);
        Juego.roj2.setVisible(true);
        Juego.roj3.setVisible(true);
        Juego.roj4.setVisible(true);
        Juego.roj5.setVisible(true);
        Juego.roj6.setVisible(true);
        Juego.roj7.setVisible(true);
        Juego.roj8.setVisible(true);
        Juego.rojo1.setIcon(rojo);
        Juego.rojo2.setIcon(rojo);
        Juego.rojo3.setIcon(rojo);
        Juego.rojo4.setIcon(rojo);
        Juego.rojo5.setIcon(rojo);
        Juego.rojo6.setIcon(rojo);
        Juego.rojo7.setIcon(rojo);
        Juego.rojo8.setIcon(rojo);
        Juego.rojo1.setBounds(905, 85, 52, 54);
        Juego.rojo2.setBounds(905, 155, 52, 54);
        Juego.rojo3.setBounds(905, 221, 52, 54);
        Juego.rojo4.setBounds(905, 287, 52, 54);
        Juego.rojo5.setBounds(905, 347, 52, 54);
        Juego.rojo6.setBounds(905, 427, 52, 54);
        Juego.rojo7.setBounds(905, 493, 52, 54);
        Juego.rojo8.setBounds(905, 559, 52, 54);
        Juego.rojo1.setVisible(true);
        Juego.rojo2.setVisible(true);
        Juego.rojo3.setVisible(true);
        Juego.rojo4.setVisible(true);
        Juego.rojo5.setVisible(true);
        Juego.rojo6.setVisible(true);
        Juego.rojo7.setVisible(true);
        Juego.rojo8.setVisible(true);

    }

    public void conteo() {
        Juego.conteoverde8 = 0;
        Juego.conteoverde7 = 0;
        Juego.conteoverde6 = 0;
        Juego.conteoverde5 = 0;
        Juego.conteoverde4 = 0;
        Juego.conteoverde3 = 0;
        Juego.conteoverde2 = 0;
        Juego.conteoverde1 = 0;
        Juego.conteorosa8 = 0;
        Juego.conteorosa7 = 0;
        Juego.conteorosa6 = 0;
        Juego.conteorosa5 = 0;
        Juego.conteorosa4 = 0;
        Juego.conteorosa3 = 0;
        Juego.conteorosa2 = 0;
        Juego.conteorosa1 = 0;
        Juego.conteorosado8 = 0;
        Juego.conteorosado7 = 0;
        Juego.conteorosado6 = 0;
        Juego.conteorosado5 = 0;
        Juego.conteorosado4 = 0;
        Juego.conteorosado3 = 0;
        Juego.conteorosado2 = 0;
        Juego.conteorosado1 = 0;
        Juego.conteoroj8 = 0;
        Juego.conteoroj7 = 0;
        Juego.conteoroj6 = 0;
        Juego.conteoroj5 = 0;
        Juego.conteoroj4 = 0;
        Juego.conteoroj3 = 0;
        Juego.conteoroj2 = 0;
        Juego.conteoroj1 = 0;
        Juego.conteorojo8 = 0;
        Juego.conteorojo7 = 0;
        Juego.conteorojo6 = 0;
        Juego.conteorojo5 = 0;
        Juego.conteorojo4 = 0;
        Juego.conteorojo3 = 0;
        Juego.conteorojo2 = 0;
        Juego.conteorojo1 = 0;
    }

    public void ver() {
        Disparo.verocho = false;
        Disparo.versiete = false;
        Disparo.verseis = false;
        Disparo.vercinco = false;
        Disparo.vercuatro = false;
        Disparo.vertres = false;
        Disparo.verdos = false;
        Disparo.veruno = false;
        Disparo.rosauno = false;
        Disparo.rosados = false;
        Disparo.rosatres = false;
        Disparo.rosacuatro = false;
        Disparo.rosacinco = false;
        Disparo.rosaseis = false;
        Disparo.rosasiete = false;
        Disparo.rosaocho = false;
        Disparo.rosadouno = false;
        Disparo.rosadodos = false;
        Disparo.rosadotres = false;
        Disparo.rosadocuatro = false;
        Disparo.rosadocinco = false;
        Disparo.rosadoseis = false;
        Disparo.rosadosiete = false;
        Disparo.rosadoocho = false;
        Disparo.rojuno = false;
        Disparo.rojdos = false;
        Disparo.rojtres = false;
        Disparo.rojcuatro = false;
        Disparo.rojcinco = false;
        Disparo.rojseis = false;
        Disparo.rojsiete = false;
        Disparo.rojocho = false;
        Disparo.rojouno = false;
        Disparo.rojodos = false;
        Disparo.rojotres = false;
        Disparo.rojocuatro = false;
        Disparo.rojocinco = false;
        Disparo.rojoseis = false;
        Disparo.rojosiete = false;
        Disparo.rojoocho = false;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Continuar;
    private javax.swing.JButton Terminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
