package practica3ipc;

import java.awt.Rectangle;

public class Principal extends javax.swing.JFrame {
    static Mastiempo mastiempo;
    static Menostiempo menostiempo;
    static Maspuntos maspuntos;
    static Menospuntos menospuntos;
    static Masvelocidad masvelocidaad;
    static Congelar congelar;
    static Tiempo tiempo;
    static String tiempodejuego;
    static Movimientoverdes movimineto;
    static Movimientorosa moverosa;
    static Movimientorosado moverosado;
    static Movimientoroj moveroj;
    static Movimientorojo moverojo;
    static Juego juego = new Juego();

    public Principal() {
        initComponents();
        tiempodejuego = Configuracion.tiempo;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        NuevoJuego = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Principal");

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Good Times", 2, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("INVASORES ESPACIALES");

        jButton1.setBackground(new java.awt.Color(0, 102, 0));
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Salir");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        NuevoJuego.setBackground(new java.awt.Color(0, 102, 0));
        NuevoJuego.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        NuevoJuego.setForeground(new java.awt.Color(0, 0, 0));
        NuevoJuego.setText("Nuevo Juego");
        NuevoJuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevoJuegoActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 102, 0));
        jButton3.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 0, 0));
        jButton3.setText("Configuración");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(0, 102, 0));
        jButton4.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 0, 0));
        jButton4.setText("Puntación Máxima");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/extra azul.png"))); // NOI18N

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/nave.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/extra azul.png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/extra azul.png"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/extra azul.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jLabel4)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addGap(83, 83, 83))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jButton1))
                .addGap(28, 28, 28))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(228, 228, 228))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(NuevoJuego)
                                .addComponent(jButton3))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel1)))
                .addContainerGap(62, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(214, 214, 214)
                .addComponent(jLabel8)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(jLabel4))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addGap(46, 46, 46)
                        .addComponent(NuevoJuego)
                        .addGap(5, 5, 5)
                        .addComponent(jLabel5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(27, 27, 27)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked

    }//GEN-LAST:event_jButton1MouseClicked

    private void NuevoJuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevoJuegoActionPerformed
       int velocidadextra = 80;
       if (Configuracion.velo == 0) {
            velocidadextra= 80;
            Juego.velocidadjuego.setText("1");
        }
        if (Configuracion.velo == 1) {
            velocidadextra = 60;
             Juego.velocidadjuego.setText("2");
        }
          
        
        
        juego.setLayout(null);
        Rectangle ultimo = Juego.Verde8.getBounds();
        Rectangle verdesiete = Juego.Verde7.getBounds();
        Rectangle verdeseis = Juego.Verde6.getBounds();
        Rectangle verdecinco = Juego.Verde5.getBounds();
        Rectangle verdecuatro = Juego.Verde4.getBounds();
        Rectangle verdetres = Juego.Verde3.getBounds();
        Rectangle verdedos = Juego.Verde2.getBounds();
        Rectangle verdearriba = Juego.Otro.getBounds();
        movimineto = new Movimientoverdes(velocidadextra,ultimo, verdesiete, verdeseis, verdecinco, verdecuatro, verdetres, verdedos, verdearriba, juego);
        movimineto.start();
        Rectangle rosaocho = Juego.rosa8.getBounds();
        Rectangle rosasiete = Juego.rosa7.getBounds();
        Rectangle rosaseis = Juego.rosa6.getBounds();
        Rectangle rosacinco = Juego.rosa5.getBounds();
        Rectangle rosacuatro = Juego.rosa4.getBounds();
        Rectangle rosatres = Juego.rosa3.getBounds();
        Rectangle rosados = Juego.rosa2.getBounds();
        Rectangle rosauno = Juego.rosa1.getBounds();
        moverosa = new Movimientorosa(velocidadextra,rosaocho, rosasiete, rosaseis, rosacinco, rosacuatro, rosatres, rosados, rosauno, juego);
        moverosa.start();
        Rectangle rosadoocho = Juego.rosado8.getBounds();
        Rectangle rosadosiete = Juego.rosado7.getBounds();
        Rectangle rosadoseis = Juego.rosado6.getBounds();
        Rectangle rosadocinco = Juego.rosado5.getBounds();
        Rectangle rosadocuatro = Juego.rosado4.getBounds();
        Rectangle rosadotres = Juego.rosado3.getBounds();
        Rectangle rosadodos = Juego.rosado2.getBounds();
        Rectangle rosadouno = Juego.rosado1.getBounds();
        moverosado = new Movimientorosado(velocidadextra,rosadoocho, rosadosiete, rosadoseis, rosadocinco, rosadocuatro, rosadotres, rosadodos, rosadouno, juego);
        moverosado.start();
        Rectangle rojocho = Juego.roj8.getBounds();
        Rectangle rojsiete = Juego.roj7.getBounds();
        Rectangle rojseis = Juego.roj6.getBounds();
        Rectangle rojcinco = Juego.roj5.getBounds();
        Rectangle rojcuatro = Juego.roj4.getBounds();
        Rectangle rojtres = Juego.roj3.getBounds();
        Rectangle rojdos = Juego.roj2.getBounds();
        Rectangle rojuno = Juego.roj1.getBounds();
        moveroj = new Movimientoroj(velocidadextra,rojocho, rojsiete, rojseis, rojcinco, rojcuatro, rojtres, rojdos, rojuno, juego);
        moveroj.start();
        Rectangle rojoocho = Juego.rojo8.getBounds();
        Rectangle rojosiete = Juego.rojo7.getBounds();
        Rectangle rojoseis = Juego.rojo6.getBounds();
        Rectangle rojocinco = Juego.rojo5.getBounds();
        Rectangle rojocuatro = Juego.rojo4.getBounds();
        Rectangle rojotres = Juego.rojo3.getBounds();
        Rectangle rojodos = Juego.rojo2.getBounds();
        Rectangle rojouno = Juego.rojo1.getBounds();
        moverojo = new Movimientorojo(velocidadextra,rojoocho, rojosiete, rojoseis, rojocinco, rojocuatro, rojotres, rojodos, rojouno, juego);
        moverojo.start();
        int minutos = 1;
        int segundos = 30;
        int intervalo = 1000;

        juego.setVisible(true);
        juego.setLocationRelativeTo(null);
        this.setVisible(false);
        if (tiempodejuego.equals("hola")) {
            minutos = 1;
            segundos = 30;

        } else {
            int tiempo = Integer.parseInt(tiempodejuego);
            if (tiempo < 60) {
                minutos = 0;
                segundos = tiempo;

            }
            if (tiempo >= 60) {
                minutos = tiempo / 60;
                int sec = minutos * 60;
                segundos = tiempo - sec;

            }
        }
        tiempo = new Tiempo(intervalo, minutos, segundos);
        tiempo.start();
    }//GEN-LAST:event_NuevoJuegoActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Principal.tiempodejuego = "hola";
        this.setVisible(false);
        puntuacion puntos = new puntuacion();
        puntos.setVisible(true);
        puntos.setLocationRelativeTo(null);

        if (Practica3IPC.jugadores == 0) {
            puntuacion.juga.setText("No hay datos todavia");
        }
        if (Practica3IPC.jugadores == 1) {
            puntuacion.uno.setText(Practica3IPC.nombrejugadores[0][0]);
            puntuacion.puno.setText(Practica3IPC.nombrejugadores[0][1]);
        }
        if (Practica3IPC.jugadores == 2) {
            int un = Integer.parseInt(Practica3IPC.nombrejugadores[0][1]);
            int dos = Integer.parseInt(Practica3IPC.nombrejugadores[1][1]);
            if (un > dos) {
                puntuacion.uno.setText(Practica3IPC.nombrejugadores[0][0]);
                puntuacion.puno.setText(Practica3IPC.nombrejugadores[0][1]);
                puntuacion.dos.setText(Practica3IPC.nombrejugadores[1][0]);
                puntuacion.pdos.setText(Practica3IPC.nombrejugadores[1][1]);
            }
            if (dos > dos) {
                puntuacion.uno.setText(Practica3IPC.nombrejugadores[1][0]);
                puntuacion.puno.setText(Practica3IPC.nombrejugadores[1][1]);
                puntuacion.dos.setText(Practica3IPC.nombrejugadores[0][0]);
                puntuacion.pdos.setText(Practica3IPC.nombrejugadores[0][1]);
            }
            if (un == dos) {
                puntuacion.uno.setText(Practica3IPC.nombrejugadores[0][0]);
                puntuacion.puno.setText(Practica3IPC.nombrejugadores[0][1]);
                puntuacion.dos.setText(Practica3IPC.nombrejugadores[1][0]);
                puntuacion.pdos.setText(Practica3IPC.nombrejugadores[1][1]);
            }
        }
        if (Practica3IPC.jugadores >= 3) {
            int[] top = new int[Practica3IPC.jugadores];
            String[] nombres = new String[Practica3IPC.jugadores];
            for (int i = 0; i < Practica3IPC.jugadores; i++) {
                top[i] = Integer.parseInt(Practica3IPC.nombrejugadores[i][1]);
                nombres[i] = Practica3IPC.nombrejugadores[i][0];
            }
            int auxiliar;
            String nombreaux;
            for (int i = 0; i < top.length; i++) {
                for (int j = i + 1; j < top.length; j++) {
                    if (top[i] < top[j]) {
                        auxiliar = top[i];
                        nombreaux = nombres[i];
                        top[i] = top[j];
                        nombres[i] = nombres[j];
                        top[j] = auxiliar;
                        nombres[j] = nombreaux;
                    }
                }
            }

            if (Practica3IPC.jugadores == 3) {
                puntuacion.uno.setText(nombres[0]);
                puntuacion.puno.setText("" + top[0]);
                puntuacion.dos.setText(nombres[1]);
                puntuacion.pdos.setText("" + top[1]);
                puntuacion.tres.setText(nombres[2]);
                puntuacion.ptres.setText("" + top[2]);
            }
            if (Practica3IPC.jugadores == 4) {
                puntuacion.uno.setText(nombres[0]);
                puntuacion.puno.setText("" + top[0]);
                puntuacion.dos.setText(nombres[1]);
                puntuacion.pdos.setText("" + top[1]);
                puntuacion.tres.setText(nombres[2]);
                puntuacion.ptres.setText("" + top[2]);
                puntuacion.cuatro.setText(nombres[3]);
                puntuacion.pcuatro.setText("" + top[3]);
            }
            if (Practica3IPC.jugadores == 5) {
                puntuacion.uno.setText(nombres[0]);
                puntuacion.puno.setText("" + top[0]);
                puntuacion.dos.setText(nombres[1]);
                puntuacion.pdos.setText("" + top[1]);
                puntuacion.tres.setText(nombres[2]);
                puntuacion.ptres.setText("" + top[2]);
                puntuacion.cuatro.setText(nombres[3]);
                puntuacion.pcuatro.setText("" + top[3]);
                puntuacion.cinco.setText(nombres[4]);
                puntuacion.pcinco.setText("" + top[4]);
            }

        }

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Configuracion configuracion = new Configuracion();
        configuracion.setVisible(true);
        configuracion.setLocationRelativeTo(null);
        this.setVisible(false);

    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton NuevoJuego;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
